version: '3.8'
services:
  web:
    build: .
    container_name: yolo_web
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    depends_on:
      - database
    volumes:
      - ./app:/app
    ports:
      - "8008:8000"
  database:
    image: "postgres"
    container_name: yolo_db
    env_file:
      - .env
    volumes:
      - yolo_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  yolo_db:
